#!/usr/bin/env bash

set -e

go get github.com/gorilla/websocket #todo vendor this or learn about the module stuff!

ls *.md | xargs misspell -error

go test ./...
go vet ./...
go fmt ./...
golint ./...
