BEGIN;

CREATE TABLE IF NOT EXISTS books (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS  books_id_uindex ON books (id);

COMMIT;
